{% set name = "pyperf" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d214aa65e085d3e4108a36152cb12f7cd0f4e7fda93b5134b43a9687c975786

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyperf = pyperf.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - pyperf
  commands:
    - pyperf --help

about:
  home: http://github.com/vstinner/pyperf/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Toolkit to run Python benchmarks'
  doc_url: http://pyperf.readthedocs.io/
  dev_url: https://github.com/vstinner/pyperf/

extra:
  recipe-maintainers:
    - langmm
