{% set name = "pyperf" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd93ccfda79214725293e95f1fa6e00cb4a64adcf1326039486d4e1f91caaa62

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyperf = pyperf.__main__:main
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=61
  run:
    - python
    - psutil >=5.9.0

# ModuleNotFoundError: No module named 'conf'  
{% set deselect_tests = " --deselect=test_misc.py::MiscTests::test_doc_version" %}
# AssertionError: Regex didn't match: 'Mean \\+- std dev: [0-9.]+ [mun]s \\+- [0-9.]+ [mun]s\\n' not found in ''
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_async_func" %}
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_async_func_with_loop_factory" %}
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_command" %}
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_func" %}
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_func_no_warmup" %}
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_time_func" %}
{% set deselect_tests = deselect_tests + " --deselect=test_examples.py::ExampleTests::test_bench_timeit" %}
# AttributeError: module 'os' has no attribute 'set_blocking'
{% set deselect_tests = deselect_tests + " --deselect=test_runner.py::TestRunner::test_pipe_with_timeout" %}  # [win]

test:
  imports:
    - pyperf
    - pyperf._bench
    - pyperf._cli
    - pyperf._cpu_utils
    - pyperf._formatter
    - pyperf._hooks
    - pyperf._metadata
    - pyperf._process_time
    - pyperf._runner
    - pyperf._timeit
    - pyperf._timeit_cli
    - pyperf._utils
    - pyperf._worker
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs pyperf.tests {{ deselect_tests }}
    - pyperf --help

about:
  home: https://github.com/psf/pyperf
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The Python pyperf module is a toolkit to write, run and analyze benchmarks.
  description: The Python pyperf module is a toolkit to write, run and analyze benchmarks.
  doc_url: https://pyperf.readthedocs.io
  dev_url: https://github.com/psf/pyperf

extra:
  recipe-maintainers:
    - langmm
