travis:
  secure:
    BINSTAR_TOKEN: BlhLbujRu5gGMSgAd81ogB3iOJX42Vh/pCmqhYF7bqBsblynoJ/JYzygW0Ia8Ib5OVgF4P1ziRDfHxo+W/jfsiWeokz4922yNTomc7rsJdeWeWnx3pZtoct0tFRxYTARwfAXGm7E73TduK7dp41Hi47v3+jRPC9dpvU43mIWituzAOiigibNURA2V+TuAk5lDMlhTBJeyleuhbmuo2lxyrBmIkI8udnthdkIClOXE9lDRfA+iem3kDqFCAtdRMz2TneTHlvaBgvSxBsthQNSe0LAfarZ/5GE2xBcFuO+nF6JZeOWBLgLRkmEhOisFQ+zNglBlO3zT+BnXwDF0BC5M9cKSTcmVINYgNuBbgVGT+vDBKkM09+SvQrH1azsEyb2poHfY56vWuksAm8ybIPgJDskXywLbL8JkebO+o88Agy8UJk+k5b/QkQIdl2WeKZ+BDkAGmiRF+jjIFV1P/A2fhqcADanFhcMLl5pR6UqadaUr4GhbXJgtmQI7TYYJdoydpvVod12/3afOam1lpuYHNgP2YHXMI3f87s24Bb/ZmRO5UoEK0p8JaCVyxdDE0mgAk2wTbGbZ+HegMi6ZEGCiHtU5x5i0FdDxmqB4812RlWaiM2e2XOYolYutdwY1TFziYPfcS4+9WpVOvqKCPs4HTyuARDhXYZSwwiJaP8uveI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
